### ISSUE TITLE
Could not load image 'paperwork'

### ISSUE THREAD

**Issue by fabrice-regnier** [openpaperwork/paperwork#597] opened 2017-02-17 14:40 UTC
Hi,

I can't see no icon for the button "paperwork " near the "plus" button. See attached file.

In the logs, it says:
```
Gtk-WARNING **: Could not load image 'paperwork': Impossible d'ouvrir le fichier « /usr/local/lib/python3.5/dist-packages/usr/share/paperwork/mainwindow/paperwork » : Aucun fichier ou dossier de ce type
```

I hope this bug haven't been reported yet.

regards,

f.
![no_paperwork_image](https://cloud.githubusercontent.com/assets/12799446/23069361/6ef522b0-f527-11e6-8fcf-6dfad4dffd1f.png)

**Comment by jflesch** [comment] 2017-02-18 16:00
I'm going to need more information:
- How did you install Paperwork ?
- On which GNU/Linux distribution ?

**Comment by fabrice-regnier** [comment] 2017-02-19 12:52
Hi,

I've installed paperwork this way (https://github.com/jflesch/paperwork/blob/unstable/doc/install.debian.markdown). I didn't used python-stdeb.

`FR-PORT:/tmp# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.0 (stretch)
Release:        9.0
Codename:       stretch

FR-PORT:/tmp# uname -a
Linux FR-PORT 4.9.0-1-amd64 #1 SMP Debian 4.9.6-3 (2017-01-28) x86_64 GNU/Linux`

regards,

f.

**Comment by jflesch** [comment] 2017-02-22 11:10
I'll try in a VM asap .. problem is, I broke my hard drive containing all my VMs ... :/

**Comment by Starch** [comment] 2017-03-15 21:51
The warning itself seems to be due to the 'icon' property to the gtkApplicationWindow in mainwindow.glade. This property seems to not be needed, an can probably be removed, as the icon is programatically set to paperwork_halo.svg afterthat.

Now, why the image is not displayed I do not know. I used to have this problem but it disappeared when i switched to unstable.

**Comment by jflesch** [comment] 2017-04-27 10:36
By 'unstable', you mean 'Debian unstable' or 'Paperwork unstable' ?

**Comment by Starch** [comment] 2017-04-27 10:53
I mean the paperwork branch unstable.

**Comment by mermetbt** [comment] 2017-05-12 05:36
Hi, I have the same problems by installing Paperwork from the Archlinux aur.
I've checked inside the directory, and the file doesn't exists.

**Comment by tYYGH** [comment] 2017-05-12 08:46
My paperwork comes from AUR, and I have nothing missing. So it is probably a missing dependency on the AUR side, not a bug with Paperwork.

**Comment by jflesch** [comment] 2017-05-12 09:02
@tYYGH or maybe a previous version of Paperwork installed it correctly. Anyway, ```setup.py``` has been modified heavily in the branch unstable, so I wouldn't be surprised if Paperwork 1.2 will fix this issue. I just need to check before closing this ticket.

**Comment by jflesch** [comment] 2017-06-01 15:00
7fba444d29b4f896fd47266d15bc28ff9bdf30fe should help too :)

**Comment by jflesch** [comment] 2017-06-01 18:37
Works perfectly in unstable :)

**Closed by jflesch** 2017-06-01 18:37 UTC
Labels: bug, need more info
