### ISSUE TITLE
Replace headerbar "Scan" button if no scanner available

### ISSUE THREAD

**Issue by bagage** [openpaperwork/paperwork#686] opened 2017-10-10 19:42 UTC
I'd like to use paperwork without a scanner. So for now I'll probably import documents directly and/or use camera. It would be nice if headerbar direct action could switch to "Import file(s)" when no scanner is available/configured. Currently it behaves like this:

![image](https://user-images.githubusercontent.com/1451988/31406996-a489b6d0-ae03-11e7-816b-effc45fcfce6.png)

If you hit the "scan" button, it'll open the Settings view.

It might be related to issue #537 and #524.

**Comment by jflesch** [comment] 2017-11-07 08:41
This ticket is actually a duplicate of #537. In both tickets, the idea is that the current button "Scan [V]" is inappropriate for some users and should be changed --> I'm closing this ticket

**Closed by jflesch** 2017-11-07 08:41 UTC
Labels: gui improvement, to study
