### ISSUE TITLE
Feature Request: Label View

### ISSUE THREAD

**Issue by jerrac** [openpaperwork/paperwork#626] opened 2017-04-23 01:04 UTC
Can we get a view for the frontend that shows all the labels in a tree view? When you click a label, the search would automatically filter to only documents that have those labels. There would also be an "unlabeled" filter.

The label structure would be based on something like what is suggested in #351. 

```amazon/electronics``` and ```amazon/books``` would translate to:

    amazon/
        electronics/
        books/

in the label view.

You can get nearly the same effect by just searching for your label. Like ```amazon/books```. But it is often a lot faster to just scroll through a list and click what you want. 

I understand, from https://github.com/openpaperwork/paperwork/issues/351#issuecomment-66106216, that paperwork is supposed to be a "scan and forget" application. If OCR were perfect, then that would work. Since OCR is not perfect, I still have to review every scan unless I want to lose a document. One of the pdf's of a scanned receipt I imported while testing failed to even get the store name correct. Which would make it rather hard to find that receipt if I searched for that store name. 

The workflow I'm after is something like this: Scan document/receipt -> doc shows up in "new" directory -> -> review each doc in the "new" directory -> file each doc when done. 

Part of the review process usually involves entering data into other applications. Like balancing checking accounts or that kind of thing.

(Side note: I cloned this repo and started poking around to see what I could figure out on my own. I'm not very good at python, but I at least know a little... Unfortunately, I have not yet figured out how to even get started... How do I even start paperwork with the changes I've made? I checked the github wiki, but couldn't find anything on that...)

(Side note 2: If this feature request is a complete no go, do you know of any good alternatives? I'm currently using the proprietary Neat Receipt. But it's Window's only and they started forcing you to have a cloud account...)

**Comment by jflesch** [comment] 2017-04-23 10:57
I think there are basically 2 features request in your ticket:

1) Labels organized as a tree : Not going to happen, see #351 
2) Label view : I think this is kind of a duplicate of #548 . The idea with #548 is to have a home screen with various statistics, including the labels. You can have a look at the second mockup here to have an idea of what is already planned : https://github.com/mjourdan/gnome-design/blob/master/paperwork/experiments/overview-pane.png .

Since both point have been / are being treated in two other tickets, I'm going to close this ticket. Feel free to comment again on this ticket if I've missed something, and feel free to comment on the others if you want to discuss one of the points.

**Comment by jflesch** [comment] 2017-04-23 11:00
> The workflow I'm after is something like this: Scan document/receipt -> doc shows up in "new" directory -> -> review each doc in the "new" directory -> file each doc when done.

Ok, I missed this 3rd point it seems :-)
What I could suggest is using a dedicated label. Either 'new' or 'treated'. The problem with a label 'new' is that you will have to add it on every new document scanned. The problem with the label 'treated' is that the automatic label guessing will end up putting it on every newly scanned document ... :/

**Comment by jflesch** [comment] 2017-04-23 11:06
I'm still going to close this ticket anyway because it's basically a mess. I need one idea per ticket, otherwise it makes it difficult for me to manage.

If you want the possibility to make your workflow work, please open another ticket dedicated to this problem/idea. I guess one thing that could be done is adding a new option "label to always add on new documents" (or something like that) in the settings.

**Closed** 2017-04-23 11:09 UTC
