### ISSUE TITLE
Install/Download failled

### ISSUE THREAD

**Issue by Bobcadence** [openpaperwork/paperwork#771] opened 2018-05-04 21:57 UTC
I would try paperwork, however the installation failled at the download ending. 

![paperwork-download-failed](https://user-images.githubusercontent.com/25250338/39654453-2a2d548e-4ff5-11e8-933d-da60555eb659.PNG)

Diagnostic info:
* Install package: paperwork_1.2.4_win64_installer.exe
* OS: Window 7 64bits

**Comment by jflesch** [comment] 2018-05-05 19:40
Hm, I do all my tests on Windows 10. I'm beginning to wonder whether it could be related to Windows 7 ...

**Comment by filipe-dias-almeida** [comment] 2018-05-12 08:59
I can confirm I also have this issue:

    Install package: paperwork_1.2.4_win64_installer.exe
    OS: Window 7 ultimate 64bits

I start the installer as admin... choose default values. Installer starts downloading paperwork.zip. Downloads all the package, next try to download something I cannot understand what (too quick the display message) and Fails with "Download Failed" message.

Maybe the download link for the second component (OCR library ? ) is broken or somehow not working for Windows 7.

I can confirm I was using an older version (1.2.1 I believe) for the past 2 years on Windows 7 64 bit. Worked flawlessly.
I really like the software and would like to continue using it. May I help diagnosing the problem in any way ?

**Comment by jflesch** [comment] 2018-05-12 09:51
Hm, ok, while I look for a solution, here is a workaround:

- You can install [1.2.1](https://github.com/openpaperwork/paperwork/releases/download/1.2.1/paperwork_1.2.1_win64_installer.exe).
- Then download the [last 1.2.4 build](https://download.openpaper.work/windows/amd64/paperwork-master-latest.zip).
- Extract the 1.2.4 build where you installed Paperwork (`c:\Program Files(x86)\Paperwork` by default). Replace the files **without** deleting anything first.

You should then be up-to-date.

If you try it, please report whether this workaround did work or not. It would prove the problem is the installer.

**Comment by filipe-dias-almeida** [comment] 2018-05-12 17:42
Thank you Jerome for your help! 

Well, here's my conclusions:

- Tried to install version 1.2.1 with the link you provided. No Luck! Installer started to download "paperwork.zip" and failed immediately. Version 1.2.4 of installer downloaded "paperwork.zip" successfully but failed on the next download (OCR library? )

- So, no luck installing V1.2.1. I tried simply unzip latest 1.2.4 build (second link you provided) to the default install folder and then simply executed paperwork.exe (need to execute it with admin rights, otherwise it hangs), but it worked. Scanner works, did not tried OCR yet (but for me OCR is not that important).

Again, I really appreciated your help. for debug purposes, in case you need me to input more info that could help you (since apparently this issue is with Windows 7), please feel free to ask and I will be glad to help!

a BIG Thumbs up! :)

**Comment by jflesch** [comment] 2018-05-12 22:57
> I tried simply unzip latest 1.2.4 build (second link you provided) to the default install folder and then simply executed paperwork.exe (need to execute it with admin rights, otherwise it hangs), but it worked. Scanner works, did not tried OCR yet (but for me OCR is not that important).

OCR won't work for sure (the paperwork-xxx.zip only contains Paperwork and most of its dependencies, but not Tesseract or its data files).
Also, I cannot guarantee it will work at all. It it works for you, good for you. But this is an untested and unsupported setup :/

**Comment by filipe-dias-almeida** [comment] 2018-05-13 07:48
> OCR won't work for sure (the paperwork-xxx.zip only contains Paperwork and most of its dependencies, but not Tesseract or its data files).>

You're correct. on the setup menu the languages combo is empty. 
I will stick with this version until further investigations, since I do not need OCR support.

**Comment by jflesch** [comment] 2018-05-15 18:49
Ok, reproduced with Win7 Pro FR.

**Comment by jflesch** [comment] 2018-05-15 21:13
I think there is a problem with NSIS + Windows 7 + https://jflesch.github.io/ . Not sure what it is yet.
I may have to move the files :/

**Comment by jflesch** [comment] 2018-05-15 21:19
Hm, https://jflesch.github.io/ + Internet explorer 8 don't work either ...

**Comment by jflesch** [comment] 2018-05-15 21:41
https://support.cybersource.com/s/article/How-do-I-enable-TLS-1-2-on-Windows-7 << fixes partially the problem
Then install fails on another download ... :/

**Comment by jflesch** [comment] 2018-05-16 20:18
Installing Windows 7 security updates seems to be good enough to solve this problem.
Anyway, I'm going to move all the files to https://download.openpaper.work/ . Should fix this issue for everybody.

**Comment by jflesch** [comment] 2018-05-16 21:06
I've updated the installer on https://openpaper.work/
Can you try and confirm it works for you please ?  (I suggest you backup `c:\program files(x86)\Paperwork` first if you already have a working installation)

**Comment by jflesch** [comment] 2018-05-17 20:45
You're welcome :)
I'm closing this ticket. Thanks for taking the time to report this issue in a first place :)

**Closed by jflesch** 2018-05-17 20:45 UTC
Labels: Windows only, bug, to study
