### ISSUE TITLE
Support importing multiple JPG files at once

### ISSUE THREAD

**Issue by nodiscc** [openpaperwork/paperwork#644] opened 2017-06-09 13:50 UTC
I have a directory containing previous document scans in JPG format (~500 files). Currently paperwork only supports importing those files manually one at a time (the import operation must be repeated for each JPG file).

It would be great if paperwork allowed importing multiple JPG files (either by selecting multiple files, or recursively in the selected import directory).

A workaround involving command line import and a simple bash loop would be ok for my use case.

**Comment by jflesch** [comment] 2017-06-09 15:09
Duplicate of #94 and #240

**Closed by jflesch** 2017-06-09 15:09 UTC
