### ISSUE TITLE
OCR never completes

### ISSUE THREAD

**Issue by Qwby** [openpaperwork/paperwork#776] opened 2018-05-21 22:07 UTC
When I scan a document and it runs OCR on the 4 different angles, the process never finishes.

This is how it looks: [Video](https://giphy.com/gifs/feadQfVBLEblypHIct/html5)

Console Output: https://pastebin.com/zFg2cBft
Additional output when closing the window:

```
INFO   paperwork.frontend.util.actions Action: [Quit (real)]
ERROR  paperwork.frontend.diag        === UNCATCHED EXCEPTION ===                                                                                                                 
Traceback (most recent call last):                                                                                                                                                
  File "/usr/local/lib/python3.6/dist-packages/paperwork/frontend/util/canvas/__init__.py", line 159, in _tick                                                                    
    drawer.on_tick()                                                                                                                                                              
  File "/usr/local/lib/python3.6/dist-packages/paperwork/frontend/mainwindow/scan.py", line 492, in on_tick                                                                       
    animator.on_tick()                                                                                                                                                            
  File "/usr/local/lib/python3.6/dist-packages/paperwork/frontend/util/canvas/animations.py", line 202, in on_tick                                                                
    self.redraw()                                                                                                                                                                 
  File "/usr/local/lib/python3.6/dist-packages/paperwork/frontend/util/canvas/drawers.py", line 183, in redraw                                                                    
    if not self._is_visible():                                                                                                                                                    
  File "/usr/local/lib/python3.6/dist-packages/paperwork/frontend/util/canvas/drawers.py", line 128, in _is_visible                                                               
    return self.compute_visibility(self.canvas.offset, self.canvas.size,                                                                                                          
  File "/usr/local/lib/python3.6/dist-packages/paperwork/frontend/util/canvas/__init__.py", line 300, in __get_offset                                                             
    x = int(self.hadjustment.get_value())                                                                                                                                         
AttributeError: 'NoneType' object has no attribute 'get_value'                                                                                                                    
ERROR  paperwork.frontend.diag        ===========================
INFO   paperwork.frontend.mainwindow  Stopping schedulers ...
INFO   paperwork.frontend.util.jobs   [Scheduler Main] Stopping
INFO   paperwork.frontend.util.jobs   [Scheduler Main] Stopped
INFO   paperwork.frontend.util.jobs   [Scheduler Search] Stopping
INFO   paperwork.frontend.util.jobs   [Scheduler Search] Stopped
INFO   paperwork.frontend.util.jobs   [Scheduler OCR] Stopping
WARNING paperwork.frontend.util.jobs   [Scheduler OCR] Tried to stop job OCR:0, but it can't be stopped
```

Additional output when hitting Ctrl+C:

```
^CProcess Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/pyinsane2/sane/daemon.py", line 172, in <module>
    main_loop(sys.argv[1], sys.argv[2:4])
  File "/usr/local/lib/python3.6/dist-packages/pyinsane2/sane/daemon.py", line 124, in main_loop
    length = os.read(fifo_c2s, length_size)
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/paperwork_backend/index.py", line 92, in run
    command = self.pipe_server.recv()
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
Exception in thread 0:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/paperwork/frontend/mainwindow/scan.py", line 205, in run
    builder=pyocr.builders.LineBoxBuilder())
  File "/usr/local/lib/python3.6/dist-packages/pyocr/tesseract.py", line 367, in image_to_string
    raise TesseractError(status, errors)
pyocr.error.TesseractError: (-2, b"read_params_file: Can't open 1\nTesseract Open Source OCR Engine v4.0.0-beta.1 with Leptonica\n")

Exception in thread 1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/paperwork/frontend/mainwindow/scan.py", line 205, in run
    builder=pyocr.builders.LineBoxBuilder())
  File "/usr/local/lib/python3.6/dist-packages/pyocr/tesseract.py", line 367, in image_to_string
    raise TesseractError(status, errors)
pyocr.error.TesseractError: (-2, b"read_params_file: Can't open 1\nTesseract Open Source OCR Engine v4.0.0-beta.1 with Leptonica\n")

Exception in thread 3:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/paperwork/frontend/mainwindow/scan.py", line 205, in run
    builder=pyocr.builders.LineBoxBuilder())
  File "/usr/local/lib/python3.6/dist-packages/pyocr/tesseract.py", line 367, in image_to_string
    raise TesseractError(status, errors)
pyocr.error.TesseractError: (-2, b"read_params_file: Can't open 1\nTesseract Open Source OCR Engine v4.0.0-beta.1 with Leptonica\n")

Exception in thread 2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/paperwork/frontend/mainwindow/scan.py", line 205, in run
    builder=pyocr.builders.LineBoxBuilder())
  File "/usr/local/lib/python3.6/dist-packages/pyocr/tesseract.py", line 367, in image_to_string
    raise TesseractError(status, errors)
pyocr.error.TesseractError: (-2, b"read_params_file: Can't open 1\nTesseract Open Source OCR Engine v4.0.0-beta.1 with Leptonica\n")

INFO   paperwork.frontend.mainwindow.scan OCR done on angle 270: -1.000000
INFO   paperwork.frontend.mainwindow.scan OCR done on angle 90: -1.000000
INFO   paperwork.frontend.mainwindow.scan OCR done on angle 180: -1.000000
INFO   paperwork.frontend.mainwindow.scan OCR done on angle 0: -1.000000
INFO   paperwork.frontend.mainwindow.scan Best: -1.000000
WARNING paperwork.frontend.util.jobs   Job OCR:0 took 407451ms and is unstoppable ! (maximum allowed: 500ms)
INFO   paperwork.frontend.util.jobs   [Scheduler OCR] Stopped
INFO   paperwork.frontend.util.jobs   [Scheduler Page boxes loader] Stopping
INFO   paperwork.frontend.util.jobs   [Scheduler Page boxes loader] Stopped
INFO   paperwork.frontend.util.jobs   [Scheduler Progress] Stopping
INFO   paperwork.frontend.util.jobs   [Scheduler Progress] Stopped
INFO   paperwork.frontend.util.jobs   [Scheduler Scan] Stopping
INFO   paperwork.frontend.util.jobs   [Scheduler Scan] Stopped
INFO   paperwork.frontend.util.jobs   [Scheduler Index search / update] Stopping
INFO   paperwork.frontend.util.jobs   [Scheduler Index search / update] Stopped
INFO   paperwork.frontend.util.jobs   [Scheduler Export] Stopping
INFO   paperwork.frontend.util.jobs   [Scheduler Export] Stopped
INFO   paperwork.frontend.mainwindow  Stopping index client ...
ERROR  paperwork.frontend.diag        === UNCATCHED EXCEPTION ===
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/paperwork/frontend/mainwindow/__init__.py", line 2337, in __actual_quit
    self.__main_win.docsearch.stop()
  File "/usr/local/lib/python3.6/dist-packages/paperwork_backend/docsearch.py", line 442, in stop
    self.index.stop()
  File "/usr/local/lib/python3.6/dist-packages/paperwork_backend/index.py", line 780, in __call__
    return self.client.remote_call(self.method_name, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/paperwork_backend/index.py", line 792, in remote_call
    self.pipe.send(cmd)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Datenübergabe unterbrochen (broken pipe)
ERROR  paperwork.frontend.diag        ===========================
INFO   paperwork.frontend.util.actions Action: [Quit (real)]
INFO   paperwork.paperwork            Stopping Pyinsane ...
ERROR  paperwork.frontend.diag        === UNCATCHED EXCEPTION ===
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/paperwork/paperwork.py", line 168, in main
    self.main_loop.run()
  File "/usr/lib/python3/dist-packages/gi/overrides/GLib.py", line 588, in run
    raise KeyboardInterrupt
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/paperwork", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/paperwork/paperwork.py", line 191, in main
    m.main(hook_func, skip_workdir_scan)
  File "/usr/local/lib/python3.6/dist-packages/paperwork/paperwork.py", line 177, in main
    pyinsane2.exit()
  File "/usr/local/lib/python3.6/dist-packages/pyinsane2/sane/abstract_proc.py", line 130, in exit
    remote_do('exit')
  File "/usr/local/lib/python3.6/dist-packages/pyinsane2/sane/abstract_proc.py", line 64, in remote_do
    os.write(fifo_c2s, length)
BrokenPipeError: [Errno 32] Datenübergabe unterbrochen (broken pipe)
ERROR  paperwork.frontend.diag        ===========================
```

Running on Kubuntu 18.04, installed via the manual method.

**Comment by jflesch** [comment] 2018-05-21 22:36
Duplicate of #774 (Ubuntu provides the same packages than Debian testing).

**Closed by jflesch** 2018-05-21 22:36 UTC
