### ISSUE TITLE
Mixed raster content compression ?

### ISSUE THREAD

**Issue by icf20** [openpaperwork/paperwork#761] opened 2018-03-20 01:15 UTC
is there any way for paperwork to archive the same compression like abbyy finereader pro ?
i am not 100% sure how they manage to reduce the size, using the image from one of my other test abbyy manage to take an 600 DPI A4 image and export it at 330kb size PDF while paperwork at 550 DPI and 75 quality give a 15 mib pdf ( i had assumed paperwork was using a huge dpi and for that reason the export was so huge but that is not the case )

exporting same image from abbyy produce a 41 mib .png file and 2.5 mib .jpg file
paperwork give a 16.5 mib .png at 100 quality and 2.1 min .jpg at quality 

so the question all this "magic" is because MRC ?

_/signed someone who wants to move away from windows_

**Comment by jflesch** [comment] 2018-03-20 07:07
https://github.com/openpaperwork/paperwork/issues/742
^ It's available in the development version, [only on Linux](https://github.com/openpaperwork/paperwork/blob/master/flatpak/README.markdown#quick-start) at the moment (see continous build 'develop')).
However, please note that this is the development version and there may be instability issues.

In short, it's a known issue. Current stable versions of Paperwork include images in PDF files as PNG which obviously make them huge. In the development version, I've used a new feature of Cairo to include them as JPEG instead. Problem is, the feature is quite new and I'm not sure it's really stable yet on Cairo side :/.

**Comment by jflesch** [comment] 2018-03-20 07:09
Since this is a duplicate of #742 , I'm going to close this ticket. Feel free to comment on it again if I missed anything.

**Closed by jflesch** 2018-03-20 07:09 UTC
Labels: optim
